name: Deploy Employee Attrition App

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with: 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ vars.AWS_REGION }}
            
            - name: Verify AWS Authentication
              run: aws sts get-caller-identity
            
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
            
            - name: Build Docker Image
              run: docker build -t employee-attrition-app:latest .
            
            - name: Tag Docker Image
              run: |
                docker tag employee-attrition-app:latest \
                ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:latest

            - name: Push Docker
              run: docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:latest